theme: jekyll-theme-minimal
remote_theme: jekyll-theme-minimal
logo: "me.jpg"
url: "https://len1995.github.io/"
title: "Glen Malone's Online CV"
description: "Recent computer science graduate of Waterford Institute of Technology with a BSc (Hons) in Entertainment Systems seeking a full time position. https://www.linkedin.com/in/glen-malone"
plugins:
  - jekyll-remote-theme
